/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cn_kotlin_myapplication_UninstallBrowserSDK */

#ifndef _Included_com_cn_kotlin_myapplication_UninstallBrowserSDK
#define _Included_com_cn_kotlin_myapplication_UninstallBrowserSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cn_kotlin_myapplication_UninstallBrowserSDK
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cn_kotlin_myapplication_UninstallBrowserSDK_init
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_cn_kotlin_myapplication_UninstallBrowserSDK
 * Method:    getNameByPid
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cn_kotlin_myapplication_UninstallBrowserSDK_getNameByPid
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
